In [2]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[0:3])

[10 20 30]


In [3]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[3:6])

[40 50 60]


In [4]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[2:])

[30 40 50 60 70 80]


In [5]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[ : 6])

[10 20 30 40 50 60]


In [6]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[-5 :-2])

[40 50 60]


In [7]:
i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[-3 :-1])

[60 70]


In [8]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[0:4:2])

[10 30]


In [9]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[0:7:3])

[10 40 70]


In [10]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[::])

[10 20 30 40 50 60 70 80]


In [11]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[ : : 2 ])

[10 30 50 70]


In [12]:
i = np.array([
[10, 20, 30, 40, 50], # 0 - 0 1 2 3 4
[60, 70, 80, 90, 100] # 1 - 0 1 2 3 4
])

print(i[1, 0:3])

[60 70 80]


In [13]:
import numpy as np

i = np.array([
[10, 20, 30, 40, 50], # 0 - 0 1 2 3 4
[60, 70, 80, 90, 100] # 1 - 0 1 2 3 4
])

print(i[0, 1:4])

[20 30 40]


In [14]:
import numpy as np

i = np.array([
[10, 20, 30, 40, 50], # 0 - 0 1 2 3 4
[60, 70, 80, 90, 100], # 1 - 0 1 2 3 4
[11, 22, 33, 44, 55] # 2 - 0 1 2 3 4
])

print(i[2, 2:4])

[33 44]


In [15]:
i = np.array([
[10, 20, 30, 40, 50], # 0 - 0 1 2 3 4
[60, 70, 80, 90, 100], # 1 - 0 1 2 3 4
[11, 22, 33, 44, 55] # 2 - 0 1 2 3 4
])

print(i[0:2, 1])

[20 70]


In [16]:
i = np.array([
[10, 20, 30, 40, 50], # 0 - 0 1 2 3 4
[60, 70, 80, 90, 100], # 1 - 0 1 2 3 4
[11, 22, 33, 44, 55], # 2 - 0 1 2 3 4
[1, 2, 3, 4, 5] # 2 - 0 1 2 3 4
])

print(i[0:3, 2])

[30 80 33]


In [17]:
import numpy as np

i = np.array([
[10, 20, 30, 40, 50], # 0 - 0 1 2 3 4
[60, 70, 80, 90, 100], # 1 - 0 1 2 3 4
[11, 22, 33, 44, 55], # 2 - 0 1 2 3 4
[1, 2, 3, 4, 5] # 2 - 0 1 2 3 4
])

print(i[0:2, 2:4])

[[30 40]
 [80 90]]


In [18]:
import numpy as np

i = np.array([
[10, 20, 30, 40, 50], # 0 - 0 1 2 3 4
[60, 70, 80, 90, 100], # 1 - 0 1 2 3 4
[11, 22, 33, 44, 55], # 2 - 0 1 2 3 4
[1, 2, 3, 4, 5] # 2 - 0 1 2 3 4
])

print(i[0:3, -3:-1])

[[30 40]
 [80 90]
 [33 44]]
